spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:trans_test;DATABASE_TO_UPPER=false;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

logging:
  level:
    root: error
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.cobi.transactional.aop.: info
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
